# Predicting from tabular data

In [1]:
import os

os.environ['KAGGLE_USERNAME'] = 'evaklimentov'
os.environ['KAGGLE_KEY'] = '2a5363f316b3cce3414b917f4f888067'

In [2]:
!kaggle datasets download -d akshaydattatraykhare/diabetes-dataset -p {'.'}

Dataset URL: https://www.kaggle.com/datasets/akshaydattatraykhare/diabetes-dataset
License(s): CC0-1.0
Downloading diabetes-dataset.zip to .
  0%|                                               | 0.00/8.91k [00:00<?, ?B/s]
100%|██████████████████████████████████████| 8.91k/8.91k [00:00<00:00, 2.08MB/s]

In [12]:
import zipfile

dataset_path = './'

with zipfile.ZipFile('diabetes-dataset.zip', 'r') as zip_ref:
    zip_ref.extractall(dataset_path)

In [6]:
import pandas as pd

csv_filepath = 'diabetes.csv'
df = pd.read_csv(csv_filepath)

df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

## Some cleaning etc.

In [13]:
mean_blood_pressure = df[df['BloodPressure'] != 0]['BloodPressure'].mean()
df['BloodPressure'] = df['BloodPressure'].replace(0, mean_blood_pressure)

In [14]:
mean_blood_pressure = df[df['SkinThickness'] != 0]['SkinThickness'].mean()
df['SkinThickness'] = df['SkinThickness'].replace(0, mean_blood_pressure)

In [15]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,72.405184,29.153420,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,12.096346,8.790942,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,24.000000,7.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,64.000000,25.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.202592,29.153420,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

...
we can continue and think about more things to do
...

## Train test split

In [16]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [17]:
X=df.drop('Outcome',axis=1)
Y=df['Outcome']

In [18]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)
print(X_train.shape,X_test.shape)

(614, 8) (154, 8)

## Train and test Random Forest classifier

In [19]:
model = RandomForestClassifier(n_estimators=10)
model = model.fit(X_train, Y_train)

In [20]:
Y_pred = model.predict(X_test)
accuracy = accuracy_score(Y_test, Y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.7857142857142857